# Support AxiomTradeAPI-py development
# Trade on Axiom: https://axiom.trade/@chipadev
# Build faster with ChipaEditor: https://chipaeditor.com

custom:
  - https://axiom.trade/@chipadev
  - https://chipaeditor.com/?utm_source=github&utm_medium=funding&utm_campaign=axiomtradeapi&utm_term=sponsor&utm_content=funding_yml
