# AxiomTradeAPI Documentation Site Configuration
# SEO-optimized Jekyll configuration for GitHub Pages

# Site settings
title: "AxiomTradeAPI - Python Library for Solana Trading Bots"
description: "Complete Python SDK for building professional Solana trading bots. Real-time WebSocket data, portfolio management, and automated trading strategies. Trusted by chipa.tech traders."
baseurl: "/AxiomTradeAPI-py"
url: "https://chipadevteam.github.io"

# Author and organization
author:
  name: "Chipa Tech"
  email: "support@chipa.tech"
  url: "https://chipa.tech"

# SEO and social media
logo: "/assets/images/axiom-logo.png"
social:
  name: "AxiomTradeAPI"
  links:
    - "https://chipa.tech"
    - "https://chipa.tech/shop"
    - "https://chipa.tech/product/create-your-bot"
    - "https://github.com/vigowalker/AxiomTradeAPI-py-1"

# GitHub Pages and Jekyll settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Quick Start"
    url: "/installation"
  - title: "API Reference"
    url: "/api-reference"
  - title: "Trading Bots"
    url: "/trading-bots"
  - title: "WebSocket Guide"
    url: "/websocket-guide"
  - title: "Examples"
    url: "/examples"
  - title: "chipa.tech"
    url: "https://chipa.tech"
    external: true

# Sidebar navigation
sidebar:
  - title: "Getting Started"
    children:
      - title: "Installation"
        url: "/installation"
      - title: "Authentication"
        url: "/authentication"
      - title: "Quick Start"
        url: "/quickstart"
  
  - title: "Core Features"
    children:
      - title: "Balance Queries"
        url: "/balance-queries"
      - title: "WebSocket Streaming"
        url: "/websocket-guide"
      - title: "Error Handling"
        url: "/error-handling"
  
  - title: "Advanced Trading"
    children:
      - title: "Trading Bot Development"
        url: "/trading-bots"
      - title: "Market Making Strategies"
        url: "/market-making"
      - title: "Arbitrage Detection"
        url: "/arbitrage"
      - title: "Risk Management"
        url: "/risk-management"
  
  - title: "Performance & Security"
    children:
      - title: "Performance Optimization"
        url: "/performance"
      - title: "Security Best Practices"
        url: "/security"
      - title: "Production Deployment"
        url: "/deployment"
  
  - title: "Resources"
    children:
      - title: "API Reference"
        url: "/api-reference"
      - title: "Code Examples"
        url: "/examples"
      - title: "Troubleshooting"
        url: "/troubleshooting"
      - title: "chipa.tech Services"
        url: "https://chipa.tech"

# SEO optimization
keywords: "solana trading bot, python trading api, cryptocurrency bot, solana api, trading automation, chipa.tech, axiom trade"

# Custom variables
custom:
  chipa_tech_url: "https://chipa.tech"
  chipa_tech_shop: "https://chipa.tech/shop"
  chipa_tech_bot_builder: "https://chipa.tech/product/create-your-bot"
  github_repo: "https://github.com/vigowalker/AxiomTradeAPI-py-1"
  discord_invite: "https://discord.gg/p7YyFqSmAz"

# Collections
collections:
  examples:
    output: true
    permalink: /:collection/:name/
  tutorials:
    output: true
    permalink: /:collection/:name/

# Markdown processing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# Syntax highlighting
highlighter: rouge

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.pyc"
  - __pycache__/

# Include files
include:
  - _pages
